In [2]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Create sample vectors and matrices
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])
M = torch.tensor([[1.0, 2.0, 3.0], 
                  [4.0, 5.0, 6.0], 
                  [7.0, 8.0, 9.0]])
N = torch.tensor([[9.0, 8.0, 7.0], 
                  [6.0, 5.0, 4.0], 
                  [3.0, 2.0, 1.0]])

print("Vector a:", a)
print("Vector b:", b)
print("Matrix M:")
print(M)
print("Matrix N:")
print(N)
print("\n")

Vector a: tensor([1., 2., 3.])
Vector b: tensor([4., 5., 6.])
Matrix M:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
Matrix N:
tensor([[9., 8., 7.],
        [6., 5., 4.],
        [3., 2., 1.]])


In [4]:
# 1. Element-wise multiplication (Hadamard product)
print("1. Element-wise multiplication (a * b):")
element_wise = a * b
print(element_wise)
print("Shape:", element_wise.shape)
print("\n")

1. Element-wise multiplication (a * b):
tensor([ 4., 10., 18.])
Shape: torch.Size([3])


In [8]:
# 1.5. Element-wise multiplication (Hadamard product)
print("1.5. Element-wise multiplication (M * N):")
element_wise = M * N
print(element_wise)
print("Shape:", element_wise.shape)
print("\n")

1.5. Element-wise multiplication (M * N):
tensor([[ 9., 16., 21.],
        [24., 25., 24.],
        [21., 16.,  9.]])
Shape: torch.Size([3, 3])


In [9]:
# 2. Dot product (inner product of vectors)
print("2. Dot product (a.dot(b)):")
dot_product1 = torch.dot(a, b)
print(dot_product1)
print("Alternative using @ operator for vectors:")
dot_product2 = a @ b
print(dot_product2)
print("\n")

2. Dot product (a.dot(b)):
tensor(32.)
Alternative using @ operator for vectors:
tensor(32.)


In [12]:

# 3. Matrix-vector multiplication
print("3. Matrix-vector multiplication (M @ a):")
matrix_vector = M @ a
print(matrix_vector)
print("Shape:", matrix_vector.shape)
print("\n")
print("Vector a:", a)
print("Vector b:", b)
print("Matrix M:")
print(M)
print("Matrix N:")
print(N)
print("\n")

3. Matrix-vector multiplication (M @ a):
tensor([14., 32., 50.])
Shape: torch.Size([3])


Vector a: tensor([1., 2., 3.])
Vector b: tensor([4., 5., 6.])
Matrix M:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
Matrix N:
tensor([[9., 8., 7.],
        [6., 5., 4.],
        [3., 2., 1.]])


In [13]:

# 4. Vector-matrix multiplication
print("4. Vector-matrix multiplication (a @ M):")
vector_matrix = a @ M
print(vector_matrix)
print("Shape:", vector_matrix.shape)
print("\n")
print("-------------------")
print("Vector a:", a)
print("Vector b:", b)
print("Matrix M:")
print(M)
print("Matrix N:")
print(N)
print("\n")

4. Vector-matrix multiplication (a @ M):
tensor([30., 36., 42.])
Shape: torch.Size([3])


-------------------
Vector a: tensor([1., 2., 3.])
Vector b: tensor([4., 5., 6.])
Matrix M:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
Matrix N:
tensor([[9., 8., 7.],
        [6., 5., 4.],
        [3., 2., 1.]])


In [15]:

# 5. Outer product (dyadic product)
print("5. Outer product (a.outer(b)):")
outer_product = torch.outer(a, b)
print(outer_product)
print("Shape:", outer_product.shape)
print("\n")

print("-------------------")
print("Vector a:", a)
print("Vector b:", b)
print("Matrix M:")
print(M)
print("Matrix N:")
print(N)
print("\n")

5. Outer product (a.outer(b)):
tensor([[ 4.,  5.,  6.],
        [ 8., 10., 12.],
        [12., 15., 18.]])
Shape: torch.Size([3, 3])


-------------------
Vector a: tensor([1., 2., 3.])
Vector b: tensor([4., 5., 6.])
Matrix M:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
Matrix N:
tensor([[9., 8., 7.],
        [6., 5., 4.],
        [3., 2., 1.]])


In [16]:

# 6. Matrix-matrix multiplication
print("6. Matrix-matrix multiplication (M @ N):")
matrix_matrix = M @ N
print(matrix_matrix)
print("Shape:", matrix_matrix.shape)
print("\n")

print("-------------------")
print("Vector a:", a)
print("Vector b:", b)
print("Matrix M:")
print(M)
print("Matrix N:")
print(N)
print("\n")

6. Matrix-matrix multiplication (M @ N):
tensor([[ 30.,  24.,  18.],
        [ 84.,  69.,  54.],
        [138., 114.,  90.]])
Shape: torch.Size([3, 3])


-------------------
Vector a: tensor([1., 2., 3.])
Vector b: tensor([4., 5., 6.])
Matrix M:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
Matrix N:
tensor([[9., 8., 7.],
        [6., 5., 4.],
        [3., 2., 1.]])


In [17]:

# 7. Element-wise matrix multiplication
print("7. Element-wise matrix multiplication (M * N):")
element_wise_matrix = M * N
print(element_wise_matrix)
print("Shape:", element_wise_matrix.shape)
print("\n")

print("-------------------")
print("Vector a:", a)
print("Vector b:", b)
print("Matrix M:")
print(M)
print("Matrix N:")
print(N)
print("\n")

7. Element-wise matrix multiplication (M * N):
tensor([[ 9., 16., 21.],
        [24., 25., 24.],
        [21., 16.,  9.]])
Shape: torch.Size([3, 3])


-------------------
Vector a: tensor([1., 2., 3.])
Vector b: tensor([4., 5., 6.])
Matrix M:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
Matrix N:
tensor([[9., 8., 7.],
        [6., 5., 4.],
        [3., 2., 1.]])


In [18]:

# 8. Using matmul function (same as @ operator)
print("8. Using torch.matmul (general matrix multiplication):")
# Vector-vector 
print("Vector-vector (torch.matmul(a, b)):")
matmul_vv = torch.matmul(a, b)
print(matmul_vv)
print("Same as dot product for 1D tensors")
print("\n")

print("-------------------")
print("Vector a:", a)
print("Vector b:", b)
print("Matrix M:")
print(M)
print("Matrix N:")
print(N)
print("\n")

8. Using torch.matmul (general matrix multiplication):
Vector-vector (torch.matmul(a, b)):
tensor(32.)
Same as dot product for 1D tensors


-------------------
Vector a: tensor([1., 2., 3.])
Vector b: tensor([4., 5., 6.])
Matrix M:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
Matrix N:
tensor([[9., 8., 7.],
        [6., 5., 4.],
        [3., 2., 1.]])


In [19]:

# Matrix-matrix
print("Matrix-matrix (torch.matmul(M, N)):")
matmul_mm = torch.matmul(M, N)
print(matmul_mm)
print("Same as M @ N")
print("\n")

Matrix-matrix (torch.matmul(M, N)):
tensor([[ 30.,  24.,  18.],
        [ 84.,  69.,  54.],
        [138., 114.,  90.]])
Same as M @ N


In [20]:

# 9. Batch matrix multiplication
print("9. Batch matrix multiplication:")
# Create batch tensors
batch_size = 2
P = torch.randn(batch_size, 3, 3)
Q = torch.randn(batch_size, 3, 4)

print("P shape:", P.shape)
print("Q shape:", Q.shape)
batch_matmul = torch.bmm(P, Q)
print("Result shape:", batch_matmul.shape)
print("First batch result:")
print(batch_matmul[0])
print("\n")

print("-------------------")
print("Vector a:", a)
print("Vector b:", b)
print("Matrix M:")
print(M)
print("Matrix N:")
print(N)
print("\n")

9. Batch matrix multiplication:
P shape: torch.Size([2, 3, 3])
Q shape: torch.Size([2, 3, 4])
Result shape: torch.Size([2, 3, 4])
First batch result:
tensor([[-4.4521e-01, -6.7227e-01, -2.6397e-03, -1.2863e-02],
        [-1.3931e+00, -4.0995e+00, -1.1388e+00, -9.5464e-01],
        [-1.0777e+00, -3.0517e+00, -1.0324e+00, -1.4789e+00]])


-------------------
Vector a: tensor([1., 2., 3.])
Vector b: tensor([4., 5., 6.])
Matrix M:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
Matrix N:
tensor([[9., 8., 7.],
        [6., 5., 4.],
        [3., 2., 1.]])


In [21]:

# 10. Cross product (only defined for 3D vectors)
print("10. Cross product (torch.cross(a, b)):")
cross_product = torch.cross(a, b)
print(cross_product)
print("Shape:", cross_product.shape)

print("-------------------")
print("Vector a:", a)
print("Vector b:", b)
print("Matrix M:")
print(M)
print("Matrix N:")
print(N)
print("\n")

10. Cross product (torch.cross(a, b)):
tensor([-3.,  6., -3.])
Shape: torch.Size([3])
-------------------
Vector a: tensor([1., 2., 3.])
Vector b: tensor([4., 5., 6.])
Matrix M:
tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
Matrix N:
tensor([[9., 8., 7.],
        [6., 5., 4.],
        [3., 2., 1.]])


/var/folders/vv/b6rpzr095z7842q169qx67ym0000gn/T/ipykernel_36917/1143116523.py:3: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/Cross.cpp:66.)
  cross_product = torch.cross(a, b)


In [35]:
x = torch.arange(4, 0, -1, dtype=torch.float32).reshape(4, 1)
y = torch.arange(0, 4, 1, dtype=torch.float32).reshape(1, 4)

print(x.shape, y.shape)

torch.Size([4, 1]) torch.Size([1, 4])


RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [38]:
x , y

(tensor([[4.],
         [3.],
         [2.],
         [1.]]),
 tensor([[0., 1., 2., 3.]]))

In [48]:
torch.zeros(4, 1)

tensor([[0.],
        [0.],
        [0.],
        [0.]])

In [49]:
torch.tanh(x)

tensor([[0.9993],
        [0.9951],
        [0.9640],
        [0.7616]])

In [50]:
x, y

(tensor([[4.],
         [3.],
         [2.],
         [1.]]),
 tensor([[0., 1., 2., 3.]]))

In [53]:
y.T * x

tensor([[0.],
        [3.],
        [4.],
        [3.]])